config/routes.rb
Kidhoo::Application.routes.draw do
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"
  get "welcome/blog"
  get "welcome/product"

  root to: 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def blog
  end

  def product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kidhoo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
</head>
<body>
<!--    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <ul>
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Contact", welcome_contact_path %></li>
          <li><%= link_to "Product", welcome_product_path %></li>
          <li><%= link_to "Blog", welcome_blog_path %></li>
        </ul>
      </div>
    </nav>  -->
    
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#Kidhoo-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../welcome/index">
          <img style="max-width:100px; margin-top: -25px;"
             src="../images/Kidhoo_Logo_A.png">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="Kidhoo-navbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Product", welcome_product_path %></li>
        <li><%= link_to "Contact", welcome_contact_path %></li>
        <!--<li><%= link_to "Blog", welcome_blog_path %></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>
    
</body>
</html>

app/views/welcome/about.html.erb
<div class="about-header">
  <div class="about-jumbotron">
    <h1>About</h1>
  </div>
</div>

<div class="container">
  <div class="mantra">
    <h3 style="color:#E77817">Our Mantra:</h3>
    <h4>Improve educational outcomes for all children, especially those with special needs.</h4>
    <!--<div class="why-details">
      <p>
        Approximately 2.5 million children with special needs in K-12 are at risk of not graduating high-school because of inadequate measurements and collaboration of their academic and behavioral goals and observations. Kidhoo transforms a proven manual and very cumbersome process used today in severe disability cases and makes it easier and accessible using latest technology. 
      </p>
    </div> -->
  </div>
</div>

<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Our Mission: </h3>
    <h4>Provide exceptional applications for parents, teachers, and other members of a child’s support community to record, measure/track, communicate and collaborate with each other within seconds so they can help tailor their approach and guidance for the child in a way which helps him/her achieve their academic and behavioral goals.</h4>
  </div>
</div>

app/views/welcome/blog.html.erb
<div class="jumbotron">
  <h2>Stuff we write about</h2>
</div>

<p>Post 1</p>
<p>Post 2</p>
<p>Post 3</p>

app/views/welcome/contact.html.erb
<div class="about-header">
  <div class="about-jumbotron">
    <h1>Contact Us</h1>
  </div>
</div>

app/views/welcome/index.html.erb
<div class ="hero">
  <div class="hero-jumbotron">
    <h1>We empower parents, educators, and therapists to improve collaboration so ALL children can succeed.</h1>
    <h3>Become a collaborator today!</h3>
    <p><a class="btn btn-primary btn-lg" role="button" href="../welcome/product">Learn more.</a></p>
  </div> <!-- Jumbotron end -->
</div> <!-- hero end -->

app/views/welcome/product.html.erb
<div class="about-header">
  <div class="about-jumbotron">
    <h1>Product</h1>
  </div>
</div>


<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Plan</h3>
    <h4>Info Here.</h4>
  </div>
</div>


<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Observe</h3>
    <h4>Info Here.</h4>
  </div>
</div>

<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Record</h3>
    <h4>Info Here.</h4>
  </div>
</div>

<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Review</h3>
    <h4>Info Here.</h4>
  </div>
</div>

<div class="container">
  <div class="mission">
    <h3 style="color:#E77817">Communicate and Collaborate</h3>
    <h4>Info Here.</h4>
  </div>
</div>